config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    resources :reviews, except: [:show, :index]
  end
  
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "400x600#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end

  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    root_url
  end

  def after_sign_out_path_for(resource)
    root_url
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show]
  def index
    @movies = Movie.all
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :category, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :set_movie
  before_action :authenticate_user!
  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_url(@movie), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= button_to "Log out", destroy_user_session_path, :method => :delete, data: { confirm: "Are you sure?" }, :class => "btn-sm delete-btn" %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
        <% if current_user&.admin? %>
        <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert info") %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% @movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :rating, style: "display: block" %>
    <%= f.text_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= movie.category %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

</div>

app/views/movies/edit.html.erb
<% if current_user&.admin? %>
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>
<% end %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your Favorite Movies</h1>
    <p><%= link_to "Sign Up To Rate The Movie", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
                   <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Category:</strong></td>
                <td><%= @movie.category %></td>
              </tr>
              <tr>
                <td><strong>Rating IMDB:</strong></td>
                <td><%= @movie.rating %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_movie_review_path(@movie) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.rating %></p>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div>
  <% if current_user&.admin? %>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
  <% end %>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
      }
     });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>

  <div>
    <%= f.label :comment, style: "display: block" %>
    <%= f.text_area :comment %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", "#"%> |
  <%= link_to "Back to movie", movie_path(@movie) %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to movie", movie_path(@movie) %>
</div>